# Generated by Django 2.2.5 on 2020-06-30 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=4, null=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Cat Type',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=80)),
                ('file', models.ImageField(upload_to='place_photos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Español'), ('zh', '汉语·中文'), ('jp', '日本語')], default='en', max_length=2)),
                ('content_id', models.CharField(blank=True, max_length=120, null=True)),
                ('content_type', models.CharField(blank=True, max_length=120, null=True)),
                ('title', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('directions', models.TextField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, max_length=150, null=True)),
                ('mapy', models.CharField(blank=True, max_length=20, null=True)),
                ('mapx', models.CharField(blank=True, max_length=20, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('created_time', models.DateField()),
                ('updated_time', models.DateField()),
                ('homepage', models.TextField(blank=True, null=True)),
                ('expagerange', models.CharField(blank=True, help_text='체험가능 연령', max_length=255, null=True)),
                ('expguide', models.TextField(blank=True, help_text='체험 내용', null=True)),
                ('heritage1', models.BooleanField(default=False, help_text='문화 유산 유무')),
                ('info_center', models.TextField(blank=True, help_text='문의 및 안내', null=True)),
                ('rest_date', models.CharField(blank=True, help_text='쉬는 날', max_length=20, null=True)),
                ('parking', models.CharField(blank=True, help_text='주차 시설', max_length=15, null=True)),
                ('use_time', models.TextField(blank=True, help_text='이용 시간', null=True)),
                ('infocenterculture', models.TextField(blank=True, help_text='문의 및 안내', null=True)),
                ('restdateculture', models.CharField(blank=True, help_text='쉬는 날', max_length=20, null=True)),
                ('usefee', models.TextField(blank=True, help_text='이용 요금', null=True)),
                ('usetimeculture', models.TextField(blank=True, help_text='이용 시간', max_length=80, null=True)),
                ('parkingculture', models.CharField(blank=True, help_text='주차 시설', max_length=15, null=True)),
                ('agelimit', models.CharField(blank=True, help_text='관람 가능연령', max_length=120, null=True)),
                ('bookingplace', models.CharField(blank=True, help_text='예매처', max_length=255, null=True)),
                ('discountinfofestival', models.TextField(blank=True, help_text='할인 정보', null=True)),
                ('eventstartdate', models.DateField()),
                ('eventenddate', models.DateField()),
                ('eventhomepage', models.TextField(blank=True, help_text='행사 홈페이지', null=True)),
                ('eventplace', models.CharField(blank=True, help_text='행사 장소', max_length=255, null=True)),
                ('placeinfo', models.TextField(blank=True, help_text='행사장 위치 안내', null=True)),
                ('playtime', models.CharField(blank=True, help_text='공연시간', max_length=100, null=True)),
                ('program', models.TextField(blank=True, help_text='행사 프로그램', null=True)),
                ('sponsor1', models.CharField(blank=True, help_text='주최자 정보', max_length=255, null=True)),
                ('sponsor1tel', models.CharField(blank=True, help_text='주최자 연락처', max_length=150, null=True)),
                ('sponsor2', models.CharField(blank=True, help_text='주관사 정보', max_length=255, null=True)),
                ('sponsor2tel', models.CharField(blank=True, help_text='주관사 연락처', max_length=150, null=True)),
                ('subevent', models.TextField(blank=True, help_text='부대행사', null=True)),
                ('usetimefestival', models.TextField(blank=True, help_text='이용요금', null=True)),
                ('expagerangeleports', models.CharField(blank=True, help_text='체험 가능 연령', max_length=255, null=True)),
                ('infocenterleports', models.TextField(blank=True, help_text='문의 및 안내', null=True)),
                ('reservation', models.TextField(blank=True, help_text='예약 안내', null=True)),
                ('restdateleports', models.CharField(blank=True, help_text='쉬는날', max_length=80, null=True)),
                ('usefeeleports', models.CharField(blank=True, help_text='입장료', max_length=255, null=True)),
                ('usetimeleports', models.CharField(blank=True, help_text='이용 시간', max_length=255, null=True)),
                ('parkingleports', models.TextField(blank=True, help_text='주차 시설', max_length=120, null=True)),
                ('checkintime', models.DateField()),
                ('checkouttime', models.DateField()),
                ('infocenterlodging', models.TextField(blank=True, help_text='문의 및 안내', null=True)),
                ('parkinglodging', models.CharField(blank=True, help_text='주차 시설', max_length=120, null=True)),
                ('reservationlodging', models.TextField(blank=True, help_text='예약 안내', null=True)),
                ('subfacility', models.TextField(blank=True, help_text='부대 시설', null=True)),
                ('fairday', models.CharField(blank=True, help_text='장서는 날', max_length=255, null=True)),
                ('infocentershopping', models.TextField(blank=True, help_text='문의 및 안내', null=True)),
                ('opentime', models.CharField(blank=True, help_text='운영 시간', max_length=200, null=True)),
                ('restdateshopping', models.CharField(blank=True, help_text='쉬는 날', max_length=255, null=True)),
                ('parkingshopping', models.CharField(blank=True, help_text='주차 시설', max_length=120, null=True)),
                ('firstmenu', models.CharField(blank=True, help_text='대표 메뉴', max_length=255, null=True)),
                ('treatmenu', models.TextField(blank=True, help_text='취급 메뉴', null=True)),
                ('infocenterfood', models.TextField(blank=True, help_text='문의 및 안내', null=True)),
                ('opentimefood', models.CharField(blank=True, help_text='영업 시간', max_length=255, null=True)),
                ('restdatefood', models.CharField(blank=True, help_text='쉬는 날', max_length=255, null=True)),
                ('reservationfood', models.TextField(blank=True, help_text='예약 안내', null=True)),
                ('parkingfood', models.CharField(blank=True, help_text='주차 시설', max_length=180, null=True)),
                ('conven', models.TextField(blank=True, help_text='편의 시설', null=True)),
                ('disablefacility', models.TextField(blank=True, help_text='장애인 편의시설', null=True)),
                ('foreignerinfocenter', models.TextField(blank=True, help_text='외국인 문의 및 안내', null=True)),
                ('parkingtraffic', models.CharField(blank=True, help_text='주차 시설', max_length=180, null=True)),
                ('cat_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='places.Cat_Type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=4, null=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Region',
            },
        ),
        migrations.CreateModel(
            name='Sub_Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=4, null=True)),
                ('name', models.CharField(max_length=80)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region', to='places.Region')),
            ],
            options={
                'verbose_name_plural': 'Town/City',
            },
        ),
        migrations.CreateModel(
            name='Sub_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=255)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='places.Place')),
            ],
            options={
                'verbose_name_plural': 'Detail Infomation',
            },
        ),
    ]
