# Generated by Django 2.2.5 on 2020-06-23 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_region',
            name='region',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='region', to='places.Region'),
        ),
    ]
