# Generated by Django 2.2.5 on 2020-06-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20200630_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='created_time',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='updated_time',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
