# Generated by Django 2.2.5 on 2020-06-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20200630_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='checkintime',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='checkouttime',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='eventenddate',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='eventstartdate',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
