# Generated by Django 2.2.5 on 2020-06-24 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20200623_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='region_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='places.Sub_Region', unique=True),
        ),
    ]
