# Generated by Django 2.2.5 on 2020-06-25 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20200624_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_type',
            name='name',
            field=models.CharField(choices=[('ko', 'Korean'), ('en', 'English'), ('es', 'Español'), ('zh', '汉语·中文'), ('jp', '日本語')], max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='region_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='places.Sub_Region'),
        ),
    ]
