# Generated by Django 2.2.5 on 2020-06-30 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20200630_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_info',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='places.Place'),
        ),
    ]
