# Generated by Django 2.2.5 on 2020-06-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20200625_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_type',
            name='name',
            field=models.CharField(choices=[('A01', 'Nature'), ('A02', 'Culture/Art/History'), ('A03', 'Leisure/Sports'), ('A04', 'Shopping'), ('A05', 'Cuisine'), ('B02', 'Accommodation')], max_length=20),
        ),
    ]
