# Generated by Django 2.2.5 on 2020-06-25 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20200625_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat_type',
            options={'verbose_name': 'Cat Type'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': 'Region'},
        ),
        migrations.AlterModelOptions(
            name='sub_info',
            options={'verbose_name_plural': 'Detail Infomation'},
        ),
        migrations.AlterModelOptions(
            name='sub_region',
            options={'verbose_name_plural': 'Town/City'},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='room',
            new_name='place',
        ),
    ]
