# Generated by Django 2.2.5 on 2020-07-06 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20200706_1227'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cat_type',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='photo',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='place',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='region',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='sub_info',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='sub_region',
            managers=[
            ],
        ),
    ]
