# Generated by Django 2.2.5 on 2020-06-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20200625_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='content_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
