# Generated by Django 2.2.5 on 2020-07-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20200706_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='eventenddate',
            field=models.DateField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='eventstartdate',
            field=models.DateField(blank=True, max_length=80, null=True),
        ),
    ]
