# Generated by Django 2.2.5 on 2020-06-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_place_content_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='sub_region',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
