# Generated by Django 2.2.5 on 2020-06-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20200627_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_type',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='cat_type',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
