# Generated by Django 2.2.5 on 2020-07-06 03:27

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20200630_2005'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='conversation',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='message',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
