# Generated by Django 2.2.5 on 2020-06-30 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('review', models.TextField()),
                ('accuracy', models.IntegerField(choices=[(0, 'I need some help!'), (1, "I'm really upset"), (2, "I've got a problem"), (3, 'Things are pretty good'), (4, 'Feeling Great!'), (5, 'Fantistic')], default=5)),
                ('safety', models.IntegerField(choices=[(0, 'I need some help!'), (1, "I'm really upset"), (2, "I've got a problem"), (3, 'Things are pretty good'), (4, 'Feeling Great!'), (5, 'Fantistic')], default=5)),
                ('communication', models.IntegerField(choices=[(0, 'I need some help!'), (1, "I'm really upset"), (2, "I've got a problem"), (3, 'Things are pretty good'), (4, 'Feeling Great!'), (5, 'Fantistic')], default=5)),
                ('location', models.IntegerField(choices=[(0, 'I need some help!'), (1, "I'm really upset"), (2, "I've got a problem"), (3, 'Things are pretty good'), (4, 'Feeling Great!'), (5, 'Fantistic')], default=5)),
                ('value', models.IntegerField(choices=[(0, 'I need some help!'), (1, "I'm really upset"), (2, "I've got a problem"), (3, 'Things are pretty good'), (4, 'Feeling Great!'), (5, 'Fantistic')], default=5)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='places.Place')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
