# Generated by Django 2.2.5 on 2020-07-06 03:27

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_list_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='list',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
